"""
License manager — hardware-locked, Ed25519-signed offline licensing.

Architecture:
  - The customer application embeds ONLY an Ed25519 PUBLIC verification key.
  - The private signing key lives exclusively on the vendor side
    (tools/license_signer/keys/, gitignored — never shipped to customers).
  - Activation is a fully offline request/response exchange:
      1. Customer generates an activation request (hw_id + customer_id,
         no secret) on this machine and sends it to the vendor.
      2. Vendor signs a license response offline using tools/license_signer/.
      3. Customer pastes the signed response back into this app.
      4. This module verifies the signature locally using only the public
         key below. No network call is made at any point.

license.dat format (XOR + base64 obfuscated, NOT a security boundary —
security comes entirely from the Ed25519 signature, not from hiding bytes):
    {"type": "trial", "start": "...", "requested_customer_id": "", "requested_hw_id": ""}
    {"type": "licensed", "response": {"payload": {...}, "signature": "..."}}
"""

import os
import json
import base64
import hashlib
import datetime
import winreg

from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PublicKey
from cryptography.exceptions import InvalidSignature

# ── Obfuscation key for license.dat at-rest storage (NOT a secret — cosmetic
# only; do not rely on this for security). Deliberately distinct from
# sync_engine.py's key so licensing carries no dependency on cloud-sync code. ──
_OBFUSCATION_KEY = b"FinPilotAI-License-Store-V2"
_DAT = os.path.join(os.environ.get("APPDATA", ""), "FinPilot AI", "license.dat")
_TRIAL_DAYS = 7

PRODUCT_ID = "FPAI"
REQUEST_VERSION = 1
REQUEST_PREFIX = "FPAI-REQ-1-"
RESPONSE_PREFIX = "FPAI-LIC-1-"

# Developer machine allowlist — these hardware IDs bypass all licensing.
# The ID is the first 16 hex chars of SHA-256(MachineGuid), uppercase.
_DEVELOPER_HW_IDS: set[str] = {
    "90DD5DDFD1D86787",  # Zohair dev machine
}

# ── Ed25519 public verification key ────────────────────────────────────────
# Safe to ship: this key can only VERIFY signatures, never create them.
# Generated by tools/license_signer/keygen.py. The matching private key is
# NOT in this repository and NEVER ships with the customer application.
_PUBLIC_KEY_B64 = "c/1jvt09ZSh813mxjdTEywWSiP3SZOq757UepXOhftk="


class HardwareIdError(Exception):
    """Raised when the Windows MachineGuid cannot be read. Callers must fail
    closed — there is no COMPUTERNAME or other weak fallback."""


# ── Hardware fingerprint (fail-closed) ─────────────────────────────────────

def _read_machine_guid() -> str:
    key = winreg.OpenKey(winreg.HKEY_LOCAL_MACHINE, r"SOFTWARE\Microsoft\Cryptography")
    try:
        guid, _ = winreg.QueryValueEx(key, "MachineGuid")
    finally:
        winreg.CloseKey(key)
    if not guid:
        raise HardwareIdError("Windows MachineGuid is empty.")
    return guid


def get_hw_id() -> str:
    """Return this machine's hardware ID, or raise HardwareIdError.
    There is no fallback identifier — if the MachineGuid can't be read,
    hardware identification has failed and callers must report that clearly
    rather than silently issuing a weaker, spoofable ID."""
    try:
        guid = _read_machine_guid()
    except HardwareIdError:
        raise
    except Exception as e:
        raise HardwareIdError(f"Could not read Windows MachineGuid: {e}") from e
    return hashlib.sha256(guid.encode()).hexdigest()[:16].upper()


# ── Ed25519 verification ───────────────────────────────────────────────────

def _public_key() -> Ed25519PublicKey:
    raw = base64.b64decode(_PUBLIC_KEY_B64)
    return Ed25519PublicKey.from_public_bytes(raw)


def _canonical_payload_bytes(payload: dict) -> bytes:
    """Deterministic byte representation of a license payload for signing/
    verification. Must exactly match tools/license_signer/sign_license.py."""
    return json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()


def verify_response(response: dict) -> tuple[bool, str, dict | None]:
    """Verify a decoded license response dict. Returns (ok, error, payload)."""
    if not isinstance(response, dict):
        return False, "Malformed license response.", None
    payload = response.get("payload")
    sig_b64 = response.get("signature")
    if not isinstance(payload, dict) or not isinstance(sig_b64, str):
        return False, "Malformed license response.", None
    required = {"product", "customer_id", "hw_id", "issued_at", "expiry",
                "license_type", "license_version"}
    if not required.issubset(payload.keys()):
        return False, "Malformed license response (missing fields).", None
    try:
        signature = base64.b64decode(sig_b64)
    except Exception:
        return False, "Malformed license response (bad signature encoding).", None
    try:
        _public_key().verify(signature, _canonical_payload_bytes(payload))
    except InvalidSignature:
        return False, "Signature verification failed — license is invalid or has been tampered with.", None
    except Exception as e:
        return False, f"Verification error: {e}", None
    if payload.get("product") != PRODUCT_ID:
        return False, "License was issued for a different product.", None
    return True, "", payload


# ── license.dat storage (XOR + base64 — obfuscation only) ─────────────────

def _xor(data: bytes) -> bytes:
    key = _OBFUSCATION_KEY
    return bytes(b ^ key[i % len(key)] for i, b in enumerate(data))


def _write_state(payload: dict) -> None:
    os.makedirs(os.path.dirname(_DAT), exist_ok=True)
    raw = json.dumps(payload).encode()
    with open(_DAT, "wb") as f:
        f.write(base64.b64encode(_xor(raw)))


def _read_state() -> dict | None:
    if not os.path.exists(_DAT):
        return None
    try:
        with open(_DAT, "rb") as f:
            raw = _xor(base64.b64decode(f.read()))
        return json.loads(raw.decode())
    except Exception:
        return None


# ── Trial management ────────────────────────────────────────────────────────

def _today_str() -> str:
    return datetime.date.today().isoformat()


def _ensure_state() -> dict:
    state = _read_state()
    if state is None:
        state = {"type": "trial", "start": _today_str(),
                  "requested_customer_id": "", "requested_hw_id": ""}
        _write_state(state)
    return state


def _trial_days_left(start: str) -> int:
    try:
        d = datetime.date.fromisoformat(start)
        elapsed = (datetime.date.today() - d).days
        return max(0, _TRIAL_DAYS - elapsed)
    except Exception:
        return 0


def _is_expired(payload: dict) -> bool:
    expiry = payload.get("expiry")
    if not expiry:
        return False  # perpetual
    try:
        return datetime.date.fromisoformat(expiry) < datetime.date.today()
    except Exception:
        return False


# ── Public API ──────────────────────────────────────────────────────────────

def get_status() -> dict:
    """Return current license status. Always call this on startup."""
    try:
        hw = get_hw_id()
    except HardwareIdError as e:
        return {"status": "hw_id_error", "hw_id": "", "days_left": None, "error": str(e)}

    # Developer bypass — unlimited access, no trial, no expiry.
    if hw in _DEVELOPER_HW_IDS:
        return {"status": "developer_unlimited", "hw_id": hw, "days_left": None}

    state = _ensure_state()

    if state.get("type") == "licensed":
        response = state.get("response")
        ok, err, payload = verify_response(response) if response else (False, "No license response stored.", None)
        if not ok:
            return {"status": "invalid", "hw_id": hw, "days_left": 0, "error": err}
        if payload["hw_id"] != hw:
            return {"status": "invalid", "hw_id": hw, "days_left": 0,
                     "error": "License is bound to a different machine."}
        if _is_expired(payload):
            return {"status": "expired", "hw_id": hw, "days_left": 0}
        return {
            "status": "licensed", "hw_id": hw, "days_left": None,
            "customer_id": payload["customer_id"],
            "license_type": payload["license_type"],
            "expiry": payload["expiry"],
        }

    days = _trial_days_left(state.get("start", _today_str()))
    if days > 0:
        return {"status": "trial", "hw_id": hw, "days_left": days}
    return {"status": "expired", "hw_id": hw, "days_left": 0}


def generate_activation_request(customer_id: str) -> dict:
    """Create and persist a new activation request for this machine.
    Returns {"ok": True, "request": "<encoded blob>"} or {"ok": False, "error": ...}.
    Contains no secret — only product/customer_id/hw_id/timestamp."""
    customer_id = (customer_id or "").strip()
    if not customer_id:
        return {"ok": False, "error": "Customer/Deployment ID is required."}
    try:
        hw = get_hw_id()
    except HardwareIdError as e:
        return {"ok": False, "error": str(e)}

    req = {
        "req_version": REQUEST_VERSION,
        "product": PRODUCT_ID,
        "customer_id": customer_id,
        "hw_id": hw,
        "requested_at": datetime.datetime.now(datetime.timezone.utc).isoformat(),
    }

    state = _ensure_state()
    if state.get("type") != "licensed":
        state["requested_customer_id"] = customer_id
        state["requested_hw_id"] = hw
        _write_state(state)

    encoded = REQUEST_PREFIX + base64.b64encode(json.dumps(req).encode()).decode()
    return {"ok": True, "request": encoded, "hw_id": hw, "customer_id": customer_id}


def _decode_response_blob(blob: str) -> dict | None:
    blob = (blob or "").strip()
    if blob.startswith(RESPONSE_PREFIX):
        blob = blob[len(RESPONSE_PREFIX):]
    try:
        raw = base64.b64decode(blob)
        return json.loads(raw.decode())
    except Exception:
        return None


def import_license_response(blob: str) -> dict:
    """Verify and (if valid) persist a vendor-signed license response.
    Returns {"success": True} or {"success": False, "error": ...}."""
    try:
        hw = get_hw_id()
    except HardwareIdError as e:
        return {"success": False, "error": str(e)}

    response = _decode_response_blob(blob)
    if response is None:
        return {"success": False, "error": "Could not parse the license response — check it was pasted in full."}

    ok, err, payload = verify_response(response)
    if not ok:
        return {"success": False, "error": err}

    if payload["hw_id"] != hw:
        return {"success": False, "error": "This license was issued for a different machine (hardware ID mismatch)."}

    state = _read_state() or {}
    expected_customer_id = state.get("requested_customer_id", "")
    if expected_customer_id and payload["customer_id"] != expected_customer_id:
        return {
            "success": False,
            "error": (f"This license is for customer '{payload['customer_id']}', but this "
                      f"installation requested activation as '{expected_customer_id}'. "
                      "Refusing to activate — wrong customer/deployment."),
        }

    if _is_expired(payload):
        return {"success": False, "error": "This license has already expired."}

    _write_state({"type": "licensed", "response": response})
    return {"success": True, "customer_id": payload["customer_id"], "license_type": payload["license_type"]}


def is_active() -> bool:
    s = get_status()
    return s["status"] in ("licensed", "trial", "developer_unlimited")
