/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/customers/create` | `/customers/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/invoices/create` | `/invoices/create`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reports` | `/reports`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/customers` | `/customers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/invoices` | `/invoices`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/suppliers` | `/suppliers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/customers/[id]` | `/customers/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/invoices/[id]` | `/invoices/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/suppliers/[id]` | `/suppliers/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/customers/create` | `/customers/create`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/invoices/create` | `/invoices/create`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/reports` | `/reports`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/customers` | `/customers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/invoices` | `/invoices`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/suppliers` | `/suppliers`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(app)'}/customers/[id]` | `/customers/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/invoices/[id]` | `/invoices/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `${'/(app)'}/suppliers/[id]` | `/suppliers/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/customers/create${`?${string}` | `#${string}` | ''}` | `/customers/create${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/invoices/create${`?${string}` | `#${string}` | ''}` | `/invoices/create${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/reports${`?${string}` | `#${string}` | ''}` | `/reports${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/customers${`?${string}` | `#${string}` | ''}` | `/customers${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/invoices${`?${string}` | `#${string}` | ''}` | `/invoices${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/suppliers${`?${string}` | `#${string}` | ''}` | `/suppliers${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/customers/create` | `/customers/create`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/invoices/create` | `/invoices/create`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/reports` | `/reports`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/customers` | `/customers`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/invoices` | `/invoices`; params?: Router.UnknownInputParams; } | { pathname: `${'/(app)'}/suppliers` | `/suppliers`; params?: Router.UnknownInputParams; } | `${'/(app)'}/customers/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/customers/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/invoices/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/invoices/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `${'/(app)'}/suppliers/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/suppliers/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `${'/(app)'}/customers/[id]` | `/customers/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/invoices/[id]` | `/invoices/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `${'/(app)'}/suppliers/[id]` | `/suppliers/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
